# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format
format = """$all$os$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Timeout for shell command
command_timeout = 100000

# color palette
palette = 'catppuccin_mocha'

continuation_prompt = '[ ](bold blue)' # duh

[status]
format = "[](bg)[$symbol$status]($style)[](bg) "
symbol = "❌"
success_symbol = ""
not_executable_symbol = "🚫"
not_found_symbol = "🔍"
sigint_symbol = "🧱"
signal_symbol = "⚡"
style = "bg:bg fg:red"
map_symbol = true
recognize_signal_code = true
pipestatus = true
pipestatus_separator = "|"
disabled = false

[sudo]
format = "[](bg)[$symbol]($style)[](bg) "
symbol = "🧙"
style = "bg:bg"
allow_windows = true
disabled = false

[username]
style_user = 'bg:bg fg:blue'
style_root = 'bg:bg fg:red'
format = "[](bg)[ $user]($style)[](bg) "
disabled = false
show_always = true

[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '❯' with the color 'bold green'
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold blue)"
vimcmd_visual_symbol = "[](bold yellow)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_replace_one_symbol = "[](bold purple)"
disabled = false

[directory]
format = "[](blue)[$path]($style)[](blue) "
truncation_length = 3
style = "bg:blue fg:bg"
read_only = " 󰌾"

[directory.substitutions]
"~" = ""
"Documents" = "󰈚"
"Downloads" = ""
"Music" = "󰎈"
"Pictures" = ""
"Projects" = ""
"Videos" = ""

".config" = ""
"dotfiles" = "󱗿"
"test" = ""
"src" = ""
"bin" = "󰘨"

"cpp" = ""
"rust" = ""
"rs" = ""
"python" = "󰌠"
"py" = "󰌠"
"lua" = ""

"nvim" = ""
"bat" = "🐱"
"lazygit" = "󰊢"
"tmux" = ""
"yazi" = "🦆"

[cmd_duration]
min_time = 2000
format = "[](bg)[󰥔](bg:bg fg:yellow)[ ](bg:yellow fg:bg)[$duration]($style)[](yellow) "
style = "bg:yellow fg:bg"
show_milliseconds = false
disabled = false
show_notifications = true

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
format = "[](bg)[$symbol]($style)[](fg:bg bg:green)[ $name $version](bg:green fg:bg)[](green) "
symbol = ""
style = "bg:bg fg:green"
detect_extensions = ["c", "h", "cpp"]

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = ""
format = "[󱎕](bg)[$symbol]($style)[](bg:flamingo fg:bg)[ $branch](bg:flamingo fg:bg)[](flamingo) "
style = "bg:bg fg:flamingo"

[git_status]
format = "[󱎕](bg)[󰊢](bg:bg fg:red)[ ](bg:red fg:bg)[$all_status$ahead_behind]($style)[](fg:red) "
style = "bg:red fg:bg"
stashed = '󰟗'
ahead = ""
behind = ""
up_to_date = ""
diverged = "󱡷"
conflicted = ""
deleted = ""
renamed = "»"
modified = ""
staged = ""
untracked = "?"
typechanged = ""

[golang]
symbol = ""
format = "[](bg)[$symbol](fg:sky bg:bg)[](fg:bg bg:sky)[ $version]($style)[](sky) "
style = "fg:bg bg:sky"

[guix_shell]
symbol = " "

[haskell]
symbol = ""
format = "[](bg)[$symbol](fg:lavender bg:bg)[](fg:bg bg:lavender)[ $version]($style)[](lavender) "
style = "fg:bg bg:lavender"

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = ""
format = "[](bg)[$symbol](fg:red bg:bg)[](fg:bg bg:red)[ $version]($style)[](red) "
style = "fg:bg bg:red"

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = ""
format = "[](bg)[$symbol](fg:blue bg:bg)[](fg:bg bg:blue)[ $version]($style)[](blue) "
style = "fg:bg bg:blue"

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "
format = "[](bg)[$symbol](fg:sapphire bg:bg)[](fg:bg bg:sapphire)[ $version]($style)[](sapphire) "
style = "fg:bg bg:sapphire"

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os]
disabled = false
style = "blue"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = '󰣇 \(btw\) '
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "📦"
format = "[](bg)[$symbol](bg:bg)[](fg:bg bg:peach)[ $version]($style)[](peach) "
style = "fg:bg bg:peach"
disabled = false

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = ""
format = '[](bg)[$symbol](fg:yellow bg:bg)[](fg:bg bg:yellow)[ $version \($pyenv_prefix $virtualenv\)]($style)[](yellow) '
style = "fg:bg bg:yellow"
pyenv_prefix = ""

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = ""
format = "[](bg)[$symbol](fg:red bg:bg)[](fg:bg bg:red)[ $version]($style)[](red) "
style = "fg:bg bg:red"

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
bg = "#222335"

